---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"
    
- environment:
    KUBECONFIG: "{{ tmp_kubeconfig }}"
    PROJECT_NAME: "{{ project_name }}"
    NAMESPACE: "{{ project_name }}"
  block:
    - name: Make sure target project {{ project_name }} exists. If not, create it.
      command: "oc new-project {{ project_name }}"
      ignore_errors: yes

    - name: Set user project
      command: "oc project {{ project_name }}"

    - name: Enable ServiceCatalogApiServers
      command: "oc patch servicecatalogapiservers cluster --type=merge -p='{\"spec\": {\"managementState\": \"Managed\"}}'"

    - name: Enable ServiceCatalogControllerManagers
      command: "oc patch servicecatalogcontrollermanagers cluster --type=merge -p='{\"spec\": {\"managementState\": \"Managed\"}}'"

    - name: Enable Template Service Broker
      ignore_errors: yes
      retries: 5
      delay: 10
      until: r_objects is succeeded
      register: r_objects
      k8s:
        state: present
        merge_type:
        - strategic-merge
        - merge
        definition: "{{ lookup('file', item ) | from_yaml }}"
      loop:
      - ./files/tsb-namespace.yml
      - ./files/tsb-og.yml
      - ./files/tsb-sub.yml
      - ./files/tsb-instance.yml

    - name: Git clone the repo if it doesn't exist
      git:
        repo: "{{ lab_repo }}"
        version: "{{ lab_branch }}"
        dest: "{{ tmp_git_location }}"
        track_submodules: yes

    - name: Deploy ODH
      command: "oc create -f {{ tmp_git_location }}/deploy/crds/opendatahub_v1alpha1_opendatahub_crd.yaml"

    - name: Deploy Seldon CRD
      command: "oc create -f {{ tmp_git_location }}/deploy/crds/seldon-deployment-crd.yaml"

    - name: Create the services & RBAC policy
      command: "{{item}}"
      with_items:
       - oc create -f {{ tmp_git_location }}/deploy/service_account.yaml
       - oc create -f {{ tmp_git_location }}/deploy/role.yaml
       - oc create -f {{ tmp_git_location }}/deploy/role_binding.yaml
       - oc adm policy add-role-to-user admin -z opendatahub-operator

    - name: Deploy ODH
      command: "oc create -f {{ tmp_git_location }}/deploy/operator.yaml"

    - pause:
      prompt: "Waiting for {{ project_name }}"
      seconds: 30

    - copy:
        src: {{ tmp_git_location }}/deploy/crds/opendatahub_v1alpha1_opendatahub_cr.yaml
        dest: {{ tmp_git_location }}/frauddetection_cr.yaml

    - name: Replace values in Seldon/Kafka deployment
        replace:
        path: {{ tmp_git_location }}/frauddetection_cr.yaml
        regexp: 'odh_deploy: false'
        replace: 'odh_deploy: true'

    - name: Insert username to kafka_admins list
      lineinfile:
        path: {{ tmp_git_location }}/deploy/kafka/vars/vars.yaml
        line: - {{ ocp_username }}

    - name: Pipenv install
      command: "{{item}}"
      with_items: 
       - "chdir=deploy/kafka/ pipenv install"

    